// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/highspec/HomepageBelow.tsx": () => import("../components/mockups/highspec/HomepageBelow.tsx"),
  "./components/mockups/highspec/HomepageConcept.tsx": () => import("../components/mockups/highspec/HomepageConcept.tsx")
};
